### ISSUE TITLE
Legend mangling in FF

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine-compare#4]
Compare the legend in Firefox (PC v35.0.1) Figure 1 to Chrome (Version 40.0.2214.94 m).

![ff_legend](https://cloud.githubusercontent.com/assets/2523089/6342017/f598c9e8-bb86-11e4-99e5-9aebcc884138.png)

**Comment by standardpixel** [comment]
It looks like my [last update](http://studio.stamen.com/berkeley/show/compare-2015-02-24/) fixed this. 

![screenshot 2015-02-24 10 11 36](https://cloud.githubusercontent.com/assets/15744/6355796/9c731058-bc0d-11e4-8b53-7c344e8708bb.png)
